### ISSUE TITLE
Get involved

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-website#15]
### Acceptance Criteria:
 _REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_
 - [x] Create page - has three tabs
    - [x] Training https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=125%3A1149
    - [x] Job vacancies https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=242%3A2092
    - [x] Volunteer opportunities https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=242%3A2356
 - [x] CMS collections
    - [x] Training events - this is the Insights CMS filtered by event tag #21  
        - [x] Get the two latest ones
    - [x] Lectures/Workshops (this is the section Working with universities) - CMS created in #30 
        - [x] Get 8 latest ones
    - [x] Vacancies - CMS created in #31 
        - [x] Get 2 latest ones
 - [x] Please refer to text limits in Figma comments
 - [x] Please follow prototype links in Figma
- [x] For vacancies and volunteer opportunities use dummy video embed unless CMT already has it
- [x] (on volunteer tab) If you click sign up, scroll down to sign up section in footer
- [x] Sign up newsletter functionality should have been created as part of #10 

--- 

### Needed from design 

Hey @bethanyios 
- [x] Provide links for where the About us button goes

**Comment by fadeomar** [comment]
I've linked the about us button to about as page for now
