### ISSUE TITLE
Update to community group page

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#95]
**Is your feature / client request related to a problem? Please describe.**
We are going to be running more ad-hoc community groups across England and we would like to make some changes to the community groups page to support this.

**Describe the solution you'd like**
On the https://www.chilternmusictherapy.co.uk/community-groups page we would like to have an interactive map of our community groups at the top and then a list of our groups underneath. 
We will have two different types of community groups:
- ad-hoc
- regular
and it would be great to be able to differentiate between the two - I'm not sure the best way of doing this? Perhaps using colour coding, or having different sections for regular groups and ad-hoc groups?
For the ad-hoc groups, we would like people to book on via eventbrite, is it possible to choose between having a button that says 'enquire now' and 'book now'?

**Describe alternatives you've considered**

**Additional context**
We would like to make this change ASAP if possible please so please can this be a priority for the next few weeks.

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Hi @katieshuster - I will pass this off to the development team. This task will need a bit of design thinking so I will ask the design team to be in touch first. Thanks!

**Comment by cyberteenie** [comment]
@katieshuster just wanted to let you know that Jem is unfortunately sick this week, but I when she is back, she will get back to you and confirm a date for the design thinking workshop. Thanks!

**Comment by jema28** [comment]
Hi @katieshuster,

I hope you're well! 

Are you free this Wednesday or Thursday to discuss this issue?

Look forward to it

**Comment by katieshuster** [comment]
Hi @jema28 

I hope you are feeling better. I could do Thursday between 10-11 and 1-3pm, are you free at any point in those times?

**Comment by jema28** [comment]
Thank you @katieshuster,

Definitely doing better. Thursday at 1pm works well for me, I'll send you an invite now

**Comment by jema28** [comment]
Hi @katieshuster,

Thanks for the call today! 

Will be recording a loom for @fadeomar's review tomorrow morning and will let you know on the few bits I want to get Fadi's confirmation on.

cc @cyberteenie

**Comment by jema28** [comment]
Hi @fadeomar,

Here are the Community Page tasks I discussed with Katie yesterday

### Tasks:

**On the community page there will now be two sections:**
1. One-off groups (these are "ad-hoc groups")
2. Regular groups (these are the ones that already exist on the page)

- [ ] 1. Add a title to the groups that already exist on the page called "Regular groups"  
   - [ ] Colour code all these cards in green (example below)

<img width="612" alt="CleanShot 2023-02-14 at 10 50 32@2x" src="https://user-images.githubusercontent.com/25960351/218714464-3b3b07cf-2c28-4d99-9b48-533ae4291abe.png">

- [ ] 2. Add a new section on the page on top of the Regular groups called "One-off groups"
   - [ ] Colour code all these cards in the dark purple (example below)

<img width="606" alt="CleanShot 2023-02-14 at 10 50 25@2x" src="https://user-images.githubusercontent.com/25960351/218714545-8b7525bb-87d2-43db-a074-35f148423ec0.png">

On top of these sections we want an interactive map (the same as we have on https://www.chilternmusictherapy.co.uk/map-of-services
- [ ] 3. Create interactive map and place above the community groups
- [ ] 4. On this map Katie would like the One-off groups and Regular groups to have colour-coded pins (in the same colours as mentioned above). I'd told her I'd check with you if this is actually feasible in Webflow

-

Katie also wants the ability to buy tickets in the group popup

- [ ] When there are tickets add a "Book on Eventbrite" button as well as the "Make an enquiry" that already exists. On this @fadeomar I also mentioned that I need to check if this would work in Webflow

cc @cyberteenie

**Comment by jema28** [comment]
Hey @katieshuster,

Fadi's at full capacity until Sunday but he can have to look at it then.

We'll keep you updated on progress/send you a design to review if needed

**Comment by jema28** [comment]
Hi @katieshuster,

We've been discussing this task internally and had a question for you:

What would you like to happen when the user clicks on the pins? I was imagining it would filter the groups so you could then click on the card? Would this work?

cc @fadeomar

**Comment by katieshuster** [comment]
That would be amazing, yes please!

**Comment by jema28** [comment]
Okay great, thanks! I'll let Fadi know :)

**Comment by jema28** [comment]
Hi @katieshuster,

Sorry for the delay on this but have got the final mockup for you now to review: 

- **Loom:** https://www.loom.com/share/7a5d4603e13d44d4867b7250f094db75
- **Wireframes**: https://www.figma.com/file/th8nLWr4WZn9FMdurh5f0c/Chiltern-Music-Therapy---Website?node-id=2104%3A21518&t=vGmO2pWuc4weAdrB-1

I shared this with Fadi and he said it will take **at least 3 days** to complete as it requires a lot of custom code (this functionality isn't native to Webflow).

Does this timing work for you? Please can you input here @cyberteenie as you know more about how much time is available for SLA?

Thanks all :)

**Comment by jema28** [comment]
@katieshuster We also discussed that hiding the map on mobile would be easier as there's not enough space to see it clearly.

Does that work for you?

**Comment by jema28** [comment]
One last question @katieshuster,

Fadi asked: if there are two types of groups at the same location on the map, which colour marker would you prefer? 

Do you prefer the one-off groups or the regular groups to show up as priority? 

Look forward to your thoughts on the above, thanks!

**Comment by katieshuster** [comment]
Hi @jema28 I think we have the time to do this so would like to go ahead please.

**Comment by jema28** [comment]
Hi @katieshuster,

Sure thing and sorry for the slight delay, was waiting for confirmation from Fadi on one of the points above.

He says that it would be best to use the colour for the regular group so there's less complexity.

@fadeomar this is now ready for dev. Can you let Katie know when you're done? Thanks!

cc @cyberteenie

**Comment by fadeomar** [comment]
Hello @katieshuster , this task is done and there are some changes to the community group CMS I've added 4 new fields in the CMS that require the new updates which are :
  - latitude 
  - longitude
  - group type
  - Eventbrite link
 
![image](https://user-images.githubusercontent.com/39485495/227916019-23ab47a7-d97a-4290-a19a-f260da89aa8e.png)


**latitude** and **longitude** are the axes of the location in the map and they are optional in case the location is online and 
**group type** is a select input with two options (one-off group and regular groups) and this required field 
and Lastly **Eventbrite link** and it's an optional field if it's set then the book button will appear otherwise will be hidden

also, I had to add a test Item for one-off groups for testing no more so that you can see the change and start to add real data also added latitude and longitude to two groups so they can appear in the map also for testing and they need to be updated with actual data if it exists or simply remove the latitude and longitude if  not

**Comment by fadeomar** [comment]
hey @katieshuster , yes please the loom video would be helpful

**Comment by katieshuster** [comment]
No problem, here you go: https://www.loom.com/share/9019271e90f148b485e377b91812428f

**Comment by fadeomar** [comment]
hey @katieshuster it wasn't that easy and it takes lots of custom code but eventually it's ready now.

**Comment by katieshuster** [comment]
Thank you, that's great!
